/*
 * FortiPAM
 *
 * REST API for configuring FortiPAM objects and settings
 *
 * API version: v1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package fpam_go

import (
	"time"
)

type Body1 struct {
	// Secret ID.
	Id int32 `json:"id"`
	// Secret name.
	Name string `json:"name"`
	// Secret target name.
	Target string `json:"target,omitempty"`
	// Enable/disable the current secret as the target privilege account.
	TargetPrivilegeAccount string `json:"target-privilege-account,omitempty"`
	// Enable/Disable using policy default for Password Changer    enable:Enable setting.    disable:Disable setting.
	PwdChgUsePolicyDefault string `json:"pwd-chg-use-policy-default,omitempty"`
	// Enable/Disable using policy default for Password Heartbeat    enable:Enable setting.    disable:Disable setting.
	HeartbeatUsePolicyDefault string `json:"heartbeat-use-policy-default,omitempty"`
	// ID of parent folder.
	Folder int32 `json:"folder"`
	// Secret template name.
	Template string `json:"template"`
	// Associated secret setting.
	AssociatedSecret int32 `json:"associated-secret,omitempty"`
	// Connect to the target server with current secret or using associate secret.    self:Connect and authenticate to server using current secret.    associate-secret:Connect and authenticate to server using associate secret.
	SshConnectWith string `json:"ssh-connect-with,omitempty"`
	// Automatically send password to server when privileged command (e.g., sudo) in SSH terminal detected.    enable:Enable setting.    disable:Disable setting.
	SshAutoPassword string `json:"ssh-auto-password,omitempty"`
	// ZTNA tag matching logic.    or:Match ZTNA tags using a logical OR operator.    and:Match ZTNA tags using a logical AND operator.
	ZtnaTagsMatchLogic string `json:"ztna-tags-match-logic,omitempty"`
	// Signing algorithm of RSA-based publicKey authentication for ssh launcher.    ssh-rsa:RSA publicKey authentication using RSA SHA-1 signing algorithm.    rsa-sha2-256:RSA publicKey authentication using RSA SHA-256 signing algorithm.    rsa-sha2-512:RSA publicKey authentication using RSA SHA-512 signing algorithm.
	RsaSignAlgo string `json:"rsa-sign-algo,omitempty"`
	// Keyboard layout (Applies to web-rdp only).    ar-101:Arabic (101).    ar-102:Arabic (102).    ar-102-azerty:Arabic (102) AZERTY.    can-mul:Canadian Multilingual Standard.    cz:Czech.    cz-qwerty:Czech (QWERTY).    cz-pr:Czech Programmers.    da:Danish.    nl:Dutch.    de:German.    de-ch:German, Switzerland.    de-ibm:German (IBM).    en-uk:English, United Kingdom.    en-uk-ext:English, United Kingdom Extended.    en-us:English, United States.    en-us-dvorak:English, United States-Dvorak.    es:Spanish.    es-var:Spanish Variation.    fi:Finish.    fi-sami:Finnish with Sami.    fr:French.    fr-ca:French, Canada.    fr-ch:French, Switzerland.    fr-be:French, Belgian.    hr:Croatian.    hu:Hungarian.    hu-101:Hungarian 101-Key.    it:Italian.    it-142:Italian (142).    ja:Japanese.    ko:Korean.    lt:Lithuanian.    lt-ibm:Lithuanian IBM.    lt-std:Lithuanian Standard.    lav-std:Latvian (Standard).    lav-leg:Latvian (Legacy).    mk:Macedonian (FYROM).    mk-std:Macedonia (FYROM) - Standard.    no:Norwegian.    no-sami:Norwegian with Sami.    pol-214:Polish (214).    pol-pr:Polish (Programmers).    pt:Portuguese.    pt-br:Portuguese (Brazilian ABNT).    pt-br-abnt2:Portuguese (Brazilian ABNT2).    ru:Russian.    ru-mne:Russian - Mnemonic.    ru-t:Russian (Typewriter).    sl:Slovenian.    sv:Swedish.    sv-sami:Swedish with Sami.    tuk:Turkmen.    tur-f:Turkish F.    tur-q:Turkish Q.    zh-sym-sg-us:Chinese (Simplified, Singapore) - US keyboard.    zh-sym-us:Chinese (Simplified) - US Keyboard.    zh-tr-hk:Chinese (Traditional, Hong Kong S.A.R.).    zh-tr-mo:Chinese (Traditional Macao S.A.R.) - US Keyboard.    zh-tr-us:Chinese (Traditional) - US keyboard.
	KeyboardLayout string `json:"keyboard-layout,omitempty"`
	// Description.
	Description string `json:"description,omitempty"`
	// Setting of password changer.    enable:Enable setting.    disable:Disable setting.
	PasswordChanger string `json:"password-changer,omitempty"`
	// Setting of password heartbeat.    enable:Enable setting.    disable:Disable setting.
	PasswordHeartbeat string `json:"password-heartbeat,omitempty"`
	// Setting of checkout.    enable:Enable setting.    disable:Disable setting.
	Checkout string `json:"checkout,omitempty"`
	// Setting of screen recording.    enable:Enable setting.    disable:Disable setting.
	Recording string `json:"recording,omitempty"`
	// Setting of approval for launching secret.    enable:Enable setting.    disable:Disable setting.
	NeedApproval string `json:"need-approval,omitempty"`
	// Setting of approval for activating secret job.    enable:Enable setting.    disable:Disable setting.
	NeedApprovalJob string `json:"need-approval-job,omitempty"`
	// Setting of proxy for secret.    enable:Enable setting.    disable:Disable setting.
	Proxy string `json:"proxy,omitempty"`
	// Setting of if secret need ssh filter profile.    enable:Enable setting.    disable:Disable setting.
	SshFilter string `json:"ssh-filter,omitempty"`
	// Setting of if secret need antivirus profile.    enable:Enable setting.    disable:Disable setting.
	AvScan string `json:"av-scan,omitempty"`
	// Setting of if seceret need dlp profile.    enable:Enable setting.    disable:Disable setting.
	DlpStatus string `json:"dlp-status,omitempty"`
	// RDP Security Level    rdp:Standard RDP encryption (web-rdp only).    tls:RDP over TLS.    nla:Network Level Authentication (CredSSP).    best-effort:Best effort (use NLA if server supports, RDP over TLS otherwise).
	RdpSecurityLevel string `json:"rdp-security-level,omitempty"`
	// Credential-less logon over NLA.    enable:Enable setting.    disable:Disable setting.
	RdpRestrictedAdminMode string `json:"rdp-restricted-admin-mode,omitempty"`
	// Setting of whether block clipboard copy & paste of rdp auth proxy.    enable:Enable setting.    disable:Disable setting.
	BlockRdpClipboard string `json:"block-rdp-clipboard,omitempty"`
	// Password Change Frequency. Repeats Monthly/Weekly/Daily    month:Repeat Monthly    week:Repeat Weekly.    day:Repeat Daily.
	PwdChgSchFrequency string `json:"pwd-chg-sch-frequency,omitempty"`
	// Password Change Interval. Ex. Every x (month/week/day(s), based on frequency)
	PwdChgSchInterval int32 `json:"pwd-chg-sch-interval,omitempty"`
	// Password change schedule Monthly Type.    first:Repeat in the first week of each month.    second:Repeat in the second week of each month.    third:Repeat in the third week of each month.    last:Repeat in the last week of each month.    last-day:Repeat on the last day of each month.    specific:Repeat on a specific day of each month.
	PwdChgSchMonthType string `json:"pwd-chg-sch-month-type,omitempty"`
	// Password change schedule month days. Repeat Monthly on specified date(s). (May be many)    1:1    2:2    3:3    4:4    5:5    6:6    7:7    8:8    9:9    10:10    11:11    12:12    13:13    14:14    15:15    16:16    17:17    18:18    19:19    20:20    21:21    22:22    23:23    24:24    25:25    26:26    27:27    28:28
	PwdChgSchMonthDay string `json:"pwd-chg-sch-month-day,omitempty"`
	// Password change schedule week days. (May be many)    sunday:Sunday.    monday:Monday.    tuesday:Tuesday.    wednesday:Wednesday.    thursday:Thursday.    friday:Friday.    saturday:Saturday.
	PwdChgSchWeekDay string `json:"pwd-chg-sch-week-day,omitempty"`
	// Password change schedule start date
	PwdChgSchStartDate time.Time `json:"pwd-chg-sch-start-date,omitempty"`
	// Heartbeat interval(mins).
	HeartbeatInterval int32 `json:"heartbeat-interval,omitempty"`
	// Password heartbeat start time
	HeartbeatStartTime time.Time `json:"heartbeat-start-time,omitempty"`
	// Setting of checkout duration(minutes).
	CheckoutDuration int32 `json:"checkout-duration,omitempty"`
	// Setting to change password on checkin    enable:Enable setting.    disable:Disable setting.
	CheckinPwdChange string `json:"checkin-pwd-change,omitempty"`
	// Setting to renew checkout duration    enable:Enable setting.    disable:Disable setting.
	CheckoutDurationRenew string `json:"checkout-duration-renew,omitempty"`
	// Setting of the max amount of times you can renew checkout.
	CheckoutRenewTimes int32 `json:"checkout-renew-times,omitempty"`
	// Setting of using encrypted tunnel.    enable:Enable setting.    disable:Disable setting.
	TunnelEncryption string `json:"tunnel-encryption,omitempty"`
	// Setting of approval-profile for secret.
	ApprovalProfile string `json:"approval-profile,omitempty"`
	// SSH filter profile.
	SshFilterProfile string `json:"ssh-filter-profile,omitempty"`
	// DLP sensor name.
	DlpSensor string `json:"dlp-sensor,omitempty"`
	// Name of Antivirus profile.
	AvProfile string `json:"av-profile,omitempty"`
	// Enable/disable inherit permission from folder.    enable:Enable setting.    disable:Disable setting.
	InheritPermission string `json:"inherit-permission"`
	// SSH service status.    up:Service up on server.    down:Service down on server.
	SshServiceStatus string `json:"ssh-service-status,omitempty"`
	// SSH service port (unset to use default).
	SshServicePort int32 `json:"ssh-service-port,omitempty"`
	// RDP service status.    up:Service up on server.    down:Service down on server.
	RdpServiceStatus string `json:"rdp-service-status,omitempty"`
	// RDP service port (unset to use default).
	RdpServicePort int32 `json:"rdp-service-port,omitempty"`
	// VNC service status.    up:Service up on server.    down:Service down on server.
	VncServiceStatus string `json:"vnc-service-status,omitempty"`
	// VNC service port (unset to use default).
	VncServicePort int32 `json:"vnc-service-port,omitempty"`
	// LDAPS service status.    up:Service up on server.    down:Service down on server.
	LdapsServiceStatus string `json:"ldaps-service-status,omitempty"`
	// LDAPS service port (unset to use default).
	LdapsServicePort int32 `json:"ldaps-service-port,omitempty"`
	// Samba service status.    up:Service up on server.    down:Service down on server.
	SambaServiceStatus string `json:"samba-service-status,omitempty"`
	// Samba service port (unset to use default).
	SambaServicePort int32 `json:"samba-service-port,omitempty"`
	// Display number for vnc (unset to use default)
	DisplayNum int32 `json:"display-num,omitempty"`
	// RDP target blacklist addresses.
	AddressBlacklist []CmdbsecretdatabaseidAddressblacklist `json:"address-blacklist,omitempty"`
	// RDP target whitelist addresses.
	AddressWhitelist []CmdbsecretdatabaseidAddresswhitelist `json:"address-whitelist,omitempty"`
	// ZTNA ems tag that controls launching
	ZtnaEmsTag []CmdbsecretdatabaseidZtnaemstag `json:"ztna-ems-tag,omitempty"`
	// Configure user permission.
	UserPermission []CmdbsecretdatabaseidUserpermission `json:"user-permission,omitempty"`
	// Configure group permission.
	GroupPermission []CmdbsecretdatabaseidGrouppermission `json:"group-permission,omitempty"`
	// Configure secret fields. Current secret credential information
	Field []CmdbsecretdatabaseField `json:"field"`
	// Third party time based one time password setting. For Fortitoken totp activation support, please use internal/secret-ftk api to update this field.
	TotpSetting []CmdbsecretdatabaseidTotpsetting `json:"totp-setting,omitempty"`
}
