/*
 * FortiPAM
 *
 * REST API for configuring FortiPAM objects and settings
 *
 * API version: v1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package fpam_go

type CmdbsecretdatabaseidTotpsetting struct {
	// Use FortiPAM as the TOTP generator.
	Status string `json:"status,omitempty"`
	// Use totp settings from template.
	UseTemplateSetting string `json:"use-template-setting,omitempty"`
	// Length of TOTP.
	TotpLength int32 `json:"totp-length,omitempty"`
	// Duration of TOTP.
	TotpDuration int32 `json:"totp-duration,omitempty"`
	// Hash algo of TOTP.
	HashType string `json:"hash-type,omitempty"`
	// Key of TOTP.
	SharedKey string `json:"shared-key,omitempty"`
}
