/*
 * FortiPAM
 *
 * REST API for configuring FortiPAM objects and settings
 *
 * API version: v1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package fpam_go

type CmdbsecretdatabaseidField struct {
	// Field ID.
	Id int32 `json:"id,omitempty"`
	// Field name.
	Name string `json:"name,omitempty"`
	// Value of the field.
	Value string `json:"value,omitempty"`
}
