/*
 * FortiPAM
 *
 * REST API for configuring FortiPAM objects and settings
 *
 * API version: v1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package fpam_go

type CmdbsecretdatabaseidAddresswhitelist struct {
	// Whitelist address/group.
	Name string `json:"name,omitempty"`
}
